export const PATH = {
    ABOUT: '/about',
    HOMEPAGE: '/',
    LOGIN: '/login',
    EDITOR: '/editor',
    SUNEDITOR: '/sun-editor',
    FORGOTPASSWORD: '/forgotpassword',
    MOBILELOGIN: '/mobilelogin',
    REGISTRATION: '/registration',
    RESETPASSWORD: '/reset-password/:token',
    VERIFYOTP: '/verifyotp',
    VERIFYEMAIL:'/activate/:token',
    LANDINGPAGE: '/landingpage',
    PERSONAL_DETAILS:'/personaldetails',
    PAYMENT_DETAILS:'/paymentdetails',
    PEDASHBOARD:'/peDashboard',
    PRDASHBOARD:'/prDashboard',
    REVIEWERDETAILS:'/reviewerDetails',
    MYSERVICES: '/myservices',
    MUDRAKOSH: '/mudraKosh',
    ARTICLEAUTHOR: '/articleAuthor',
    READINGLISTING: '/readingListing', 
    MYPROFILE: '/myprofile', 
    EDITPROFILE: '/editprofile',
    SUBMITARTICLE: '/submitarticle',
    EDITARTICLE:'/editarticle/:id',
    POPUPSCREENS:'/popoupscreens',
    PREVIEWPROFILE:'/previewprofile',
    CONTACT_US: '/contactus',
    RESOURCE_CENTER: '/resourcecentre',
    PLAY_LIST: '/playlist',
    PRESENTATIONS: '/presentations',
    FAQ: '/faq',
    COOKIE: '/cookie',
    COUNSIL: '/council',
    ADVISORY: '/advisory',
    WIP: '/work-in-progress-kaashi',
    WIP_AKASHGANGA: '/work-in-progress-akashganga',
    BROWSE: '/browse',
    MEMBER_DETAILS: '/member-details',
    TERMS: '/terms',
    PRIVACY_POLICY: '/privacy-policy',
    TEAMS: '/teams',
    FOUNDER_DETAILS: '/founder-details',
    ERROR: '*',
    DASHBOARD: {
        HOME: '/dashboard',
        PEER_REVIEWER: '/dashboard/peer-reviewer',
        PUBLISHING_EDITOR: '/dashboard/publishing-editor',
    },
    MEMBERS: {
        JAGDISH_SETH: '/member-details/jagdish-seth',
        AMITABH_RAJAN: '/member-details/amitabh-rajan',
        PROF_GAUR: '/member-details/prof-ramesh-gaur',
        RAJIV_BHATIA: '/member-details/rajiv-bhatia',
        BHIMARYA_MATRI: '/member-details/bhimaraya-matri',
        HARIVANSH_CHATURVEDI: '/member-details/harivansh-chaturvedi',
        SUCHIRA: '/member-details/suchiradipta-bhattacharjee',
        SUBIR: '/member-details/subir-verma',
        SANJAY_SHRIVASTAVA: '/member-details/sanjay-shrivastava',
        SADHANA_RAUT: '/member-details/sadhana-raut',
        RISHI_KALPAL: '/member-details/rishi-kalpal',
        NANDINI: '/member-details/nandini',
        BHARAT_WAKLU: '/member-details/bharat-waklu',
        ASHA: '/member-details/asha',
        ANMOL_PANDIT: '/member-details/anmol-pandit',
        PRITAM_SINGH: '/member-details/late-pritam-singh',
        SID_MITRA: '/member-details/late-sid-mitra',
        SRIPANA_BASU: '/member-details/sriparna-basu',
        KUMARASWAMY: '/member-details/kumaraswamy',
        SAM: '/member-details/sam',
        NEERAJ_KAPOOR: '/member-details/neeraj-kapoor',
        RUPAMANJARI_GHOSH: '/member-details/rupamanjari-ghosh',
        ANKUR_SEGON: '/member-details/ankur-segon',
        RAJIV_SINGLA: '/member-details/rajiv-singla'
    },
    DASHBOARD: {
        DASHBOARD: '/dashboard',
        HOME: '/dashboard',
        SUBMIT_ARTICLE: '/dashboard/submit-article',
        EDIT_ARTICLE: '/dashboard/edit-article/:id',
        MY_ARTICLE_DRAFT: '/myArticle/draft',
        MY_ARTICLE_UNDER_REVIEW: '/myArticle/under-review',
        MY_ARTICLE_APPROVED: '/myArticle/approved',
        MY_ARTICLE_REJECTED: '/myArticle/rejected',
        MY_ARTICLE_PUBLISHED: '/myArticle/published',
        PUBLISHING_EDITOR: '/dashboard/publishing-editor',
        PEER_REVIEWER: '/dashboard/peer-reviewer',
        PE_VIEW_ARTICLE: '/dashboard/peer-reviewer/view-article',
        ARTICLE: {
            VIEW_REPORT: '/dashboard/article/:id/view-report',
        }
    }
}